### ISSUE TITLE
Ozmo T8: Only sounds works

### ISSUE THREAD

**Issue by icorn** [nicoduj/homebridge-deebotEcovacs#29]
I use the Deebot Ozmo T8 AIVI. Both in HomeKit and in HomeBridge, only the switch to play the sound works. The other switches do nothing (I tried both HomeKit and HomeBridge).

I'm using version 1.0.2.

**Comment by mrbungle64** [comment]
@nicoduj 

Version >= 0.4.14 of the library has support for T8 AIVI

**Comment by icorn** [comment]
Cool, thanks @mrbungle64, I hope for the next version then.

**Comment by nicoduj** [comment]
Hi,

will try to update asap, sorry, not available a lot those days.

**Comment by FeepDryer** [comment]
I got my Deebot Ozmo T8 (without AIVI) since yesterday. I have the same problem as described here. Only the sound button works in HomeBridge and HomeKit. Is there any solution to this problem? 
Thanks for your help!

**Comment by nicoduj** [comment]
Hi, logs would be much appreciated , however I don’t have a lot of time those days so can’t promise anything

**Comment by mrbungle64** [comment]
@nicoduj  @FeepDryer 

I suspect that the T8 has a different device class than the T8 AIVI.
I will try to find out this device class so I can add it to the configuration file of library.

**Comment by mrbungle64** [comment]
@FeepDryer 

Can you please install this library on your system?

1)
```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

2) change email and password in the file `app2.js`

3) execute the example app
```bash
NODE_ENV=dev node app2.js | grep -E 'class:'
```

4) post the output
should look like this:
```bash
class: 'y79a7u',
```

**Comment by FeepDryer** [comment]
@mrbungle64 

Thanks for your support. Here is the output: 

`
class: 'h18jkh',
`

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Thanks for your support. Here is the output:
> 
> `class: 'h18jkh',`

@FeepDryer  :+1: 

@nicoduj 

I published 0.4.19 incl. support for the Ozmo T8.

https://github.com/mrbungle64/ecovacs-deebot.js/releases/tag/0.4.19
https://www.npmjs.com/package/ecovacs-deebot/v/0.4.19

**Comment by FeepDryer** [comment]
Hi there, 

just installed the version 1.2.0 of Deebotecovacs. But my T8 is still not working. Strangely now even the sound button has no function anymore. Am I right with the assumption that the T8 should be supported in the new update? If this is the case I have to do some troubleshooting. But if the T8 is not yet supported anyway, I can save myself the troubleshooting.

**Comment by mrbungle64** [comment]
Hi @FeepDryer 

> Am I right with the assumption that the T8 should be supported in the new update?

Yes, you're right. But unfortunately there was a bug in the library.

@nicoduj 
I already fixed it. Should be working now with the latest version
https://github.com/mrbungle64/ecovacs-deebot.js/releases/tag/0.4.21
https://www.npmjs.com/package/ecovacs-deebot/v/0.4.21

**Comment by mrbungle64** [comment]
> Hi there,
> 
> just installed the version 1.2.0 of Deebotecovacs. But my T8 is still not working. Strangely now even the sound button has no function anymore. Am I right with the assumption that the T8 should be supported in the new update? If this is the case I have to do some troubleshooting. But if the T8 is not yet supported anyway, I can save myself the troubleshooting.

Hi @FeepDryer 

have you already tried if your T8 is working with version 1.2.1 of homebridge-deebotecovacs?
